### ISSUE TITLE
Multiple Endogenous Variables

### ISSUE THREAD

**Issue by Rturati** [kolesarm/ShiftShareSE#1]
Dear authors,

Thank you for your research. I was wondering: your methods works with multiple endogenous variables (e.g. two endogenous variables), or it works with only one endogenous variable at the time?

Thank you 
Best
Riccardo

**Comment by kolesarm** [comment]
Sorry for the late reply as I missed your issue. Yes, our methods can be extended to this case, but it is currently not implemented in the package. In the latest commit, https://github.com/kolesarm/ShiftShareSE/commit/0371519d3c1fb42abc22e263dfb9df967a3439e7 I have added Section 3 to the [vignette](https://github.com/kolesarm/ShiftShareSE/blob/master/doc/ShiftShareSE.pdf) that derives the formulas if you'd like to implement the methods yourself.
