### ISSUE TITLE
Possible missing intercept in regressions on lines 95 and 103?

### ISSUE THREAD

**Issue by jagman88** [kolesarm/ShiftShareSE#2]
https://github.com/kolesarm/ShiftShareSE/blob/8d0031d936ba25d64efb8c073e0e54a6c3c9dd3d/R/iv.R#L95

I've been playing around with the code and noticed that the regression to find \hat{\Xs} does not include an intercept term. Because the regressions prior to this (e.g. on lines 92, 93, 94) involve the controls matrix, which itself is derived from an `lm` regression formula, these will include intercept terms by default. But the regression on line 95 does not:
`hX <- stats::lm.fit(y=ddX, x=W)$coefficients #  \hat{\Xs}`

In playing around with the IV regression for the ADH dataset provided, I have found that it can make quite some difference whether this intercept is included or not. Especially when regression weights are used (E.g. lines 100-106), I found that the AKM standard errors can differ up to the second decimal point, depending on the intercept. 

What I cannot work out is whether the intercept **should** be there or not. I understand that \ddot{X} is a residual term, and so should be mean zero, and so the intercept should not be necessary in the regression to construct \hat{\Xs}. But then, it turns out to make some difference to the estimates... So is this just a small sample issue, or is something else going on?

**Comment by kolesarm** [comment]
There *should not be* an intercept in the regression
https://github.com/kolesarm/ShiftShareSE/blob/a264417309cb5d35810f4cc76db626bf865ea0a8/R/iv.R#L95

The reason for this is that goal of the the above regression is to project `ddX` onto the sectoral space, that is, write `ddX` as an (approximate) sum of sector-level shocks, `ddX[i] = sum(W[i, ]*hX)` (without intercept).
