### ISSUE TITLE
Definition of W matrix

### ISSUE THREAD

**Issue by wagfoliveira** [kolesarm/ShiftShareSE#3]
Dear authors,

First of all, thank you very much for providing the code for your paper.

I am implementing it in an application for a panel of 722 commuting zones x 7 periods and I have a question regarding the definition of the W matrix.

I would like to better understand the structure of the W matrix. I saw that the AKM$W matrix, which is for a 2-period application, has shares disposed in a "diagonal", like the first 722 rows (czones), 375 columns (sectors) show shares for t = 1 and then the last 722 rows, last 375 columns for t = 2 and then the rest filled with zeros. Did I understand it right?

In my application, shares should not vary through time, so I was wondering whether the W matrix in my case should just repeat the shares 7 times in a diagonal, ending up with a matrix of 5054 rows (722 x 7) and the number of colums equal s x 7, where s is the number of sectors, is that right?

Best regards,
Wagner F. Oliveira
PhD Candidate at FGV EPGE

**Comment by kolesarm** [comment]
If you have panel data, and the shares don't vary, then just replicate the same share matrix 7 times, along the block-diagonal.

We discuss the reasoning in Section 5.2 of the paper: with panel data the share matrix elements W[i, s] measure the exposure of location i to shock s, but in this case, s is a time-industry pair, and region is a region-period pair (j,t). The first 772 rows correspond to locations in period 1, the next 772 to locations in period 2 etc. The first 375 columns correspond to shocks to industries in period 1, the next 375 columns to shocks in period 2 etc.

**Comment by wagfoliveira** [comment]
Thanks for the answer!
Best,
Wagner
